server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: kiri-engine-integration
  
  # Configuraci贸n para archivos multipart
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 500MB
      file-size-threshold: 2KB

# Configuraci贸n de KIRI Engine API
kiri:
  engine:
    api:
      key: ${KIRI_ENGINE_API_KEY:kiri_nEafHXmu9nBj6PTf_Zt8mFfWiTXb0EUU833AbR2Gz00}
      base-url: ${KIRI_ENGINE_BASE_URL:https://api.kiriengine.app/api/v1}

# Configuraci贸n de Gemini API para Avatares
gemini:
  apiKey: ${GEMINI_API_KEY:YOUR_GEMINI_API_KEY}
  apiUrl: ${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta}
  model: ${GEMINI_MODEL:gemini-pro}
  temperature: ${GEMINI_TEMPERATURE:0.7}
  maxOutputTokens: ${GEMINI_MAX_TOKENS:1024}
  timeoutMs: ${GEMINI_TIMEOUT:30000}

# Configuraci贸n de logging
logging:
  level:
    com.disrupton: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 