server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: kiri-engine-integration
  
# Configuración para archivos multipart
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 500MB
      file-size-threshold: 2KB

# Configuración de KIRI Engine API
kiri:
  engine:
    api:
      key: ${KIRI_ENGINE_API_KEY:kiri_nEafHXmu9nBj6PTf_Zt8mFfWiTXb0EUU833AbR2Gz00}
      base-url: ${KIRI_ENGINE_BASE_URL:https://api.kiriengine.app/api/v1}

# Configuración de Firebase
firebase:
  project:
    id: ${FIREBASE_PROJECT_ID:disrupton2025}
    storage:
      bucket: ${FIREBASE_STORAGE_BUCKET:disrupton2025.firebasestorage.app}
  service:
    account:
      file: ${FIREBASE_SERVICE_ACCOUNT_FILE:firebase-service-account.json}

# Configuración de logging
logging:
  level:
    com.disrupton: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Confuguración de Culqi
culqi:
  api:
    key: sk_test_xxxxxxxxxxxxxxxxxxxxxxxxx
    url: https://api.culqi.com/v2

# Plan ID en Culqi (crea un plan en Culqi Dashboard para S/15 mensuales)
  plan:
    monthly_plan_id: plan_XXXXXXXX

# URL pública para webhooks (configurar en Culqi Dashboard)
app:
  webhook:
    base-url: https://localhost:8080/api/webhooks/culqi
